### ISSUE TITLE
[Question] How to ignore a whole model ?

### ISSUE THREAD

**Issue by chenxxzhe** [yanmarinich/prisma-types-generator#2]
I don't want to generate DTO for some Model,  How can I ignore these model ?

**Comment by yanmarinich** [comment]
I guess there should be a new request for this feature unfortunately I don't have much time at the moment to implement this functionality but anyone is free to contribute)

**Comment by yanmarinich** [comment]
> I don't want to generate DTO for some Model, How can I ignore these model ?

I guess there should be a new request for this feature unfortunately I don't have much time at the moment to implement this functionality but anyone is free to contribute)
