### ISSUE TITLE
[Question/Bug?] Incompatible ConnectDto with Prisma.WhereUniqueInput IF multiple unique indexes

### ISSUE THREAD

**Issue by CamilleHbp** [yanmarinich/prisma-types-generator#4]
Hello! First of all, thanks for this amazing generator. We find it really useful in our project. One source of truth for DTOs, Entities, Swagger and validators. This is great! 

We encountered a problem but we don't know if I should ask you or the Prisma team. When you generate a ConnectDTO, those are incompatible with Prisma types. 

The types are incompatible between the `connect` field in the `Prisma.create` and the `ConnectDTO`.

```
Type 'CreateBusinessRelationUserRelationInputDto' is not assignable to type 'UserCreateNestedOneWithoutBusinessRelationsInput'.ts(2322)
index.d.ts(13576, 5): The expected type comes from property 'user' which is declared here on type '(Without<BusinessRelationCreateInput, BusinessRelationUncheckedCreateInput> & BusinessRelationUncheckedCreateInput) | (Without<...> & BusinessRelationCreateInput)'
```

The reason is a conflict between the `WhereUniqueInput` from Prisma and the`ConnectDTO` from your lib. The `WhereUniqueInput` does some weird stuff with types and expect an id with `string | number` since there is a second possible unique index, email, with a `string` type.

```
Type 'CreateBusinessRelationUserRelationInputDto' is not assignable to type 'UserCreateNestedOneWithoutBusinessRelationsInput'.
  Types of property 'connect' are incompatible.
    Type 'ConnectUserDto' is not assignable to type 'UserWhereUniqueInput | undefined'.
      Type 'ConnectUserDto' is not assignable to type '{ id: string | number; email: string | number; } & { email?: string | undefined; id?: number | undefined; AND?: UserWhereInput | UserWhereInput[] | undefined; ... 17 more ...; role?: (Without<...> & RoleWhereInput) | ... 1 more ... | undefined; }'.
        Type 'ConnectUserDto' is not assignable to type '{ id: string | number; email: string | number; }'.
          Types of property 'id' are incompatible.
            Type 'number | undefined' is not assignable to type 'string | number'.
              Type 'undefined' is not assignable to type 'string | number'.ts(2322)
index.d.ts(13576, 5): The expected type comes from property 'user' which is declared here on type '(Without<BusinessRelationCreateInput, BusinessRelationUncheckedCreateInput> & BusinessRelationUncheckedCreateInput) | (Without<...> & BusinessRelationCreateInput)'
(property) user: Prisma.UserCreateNestedOneWithoutBusinessRelationsInput
```

This is the part that creates the problem:
```
Type 'ConnectUserDto' is not assignable to type '{ id: string | number; email: string | number; }'.
          Types of property 'id' are incompatible.
            Type 'number | undefined' is not assignable to type 'string | number'.
```

I solve this at the moment by setting the object manually like this:
```ts
function (myDto: CreateUserDto) {
   const connectUser =  {
          connect: {
            id: dto.data.user.connect.id,
            email: dto.data.user.connect.email,
          },
        };

      this.prisma.businessRelation.create({
        data: {
          ...dto.data,
          user: connectUser,
        }
      }),
}
```

Do you have any idea how to solve this in a more elegant way? I have to do this for all connections in all services and it takes a bit of time ^^

Thank you!

**Comment by yanmarinich** [comment]
Hi) Maybe you are willing to contribute? I'm not sure when I'm able to take a look at my repos with current workload)

**Comment by CamilleHbp** [comment]
Hi! :) I have not yet managed to look into it but I'll try to! I've already forked and made a few modifications for myself, I'll try to make a few PR and you could look whether or not that is useful for the project. Thanks for the answer! :)

**Comment by CamilleHbp** [comment]
I did a few unrelated PRs (#5 , #6 , #7 ) that I need in my project since I'm using Prisma in an external NPM package. Feel free to review them and reject them if you feel they are not required for this project! 😅  I'll try to look into the Connect DTOs later. 🙂
