### ISSUE TITLE
[Question] Is the project dead?

### ISSUE THREAD

**Issue by CamilleHbp** [yanmarinich/prisma-types-generator#9]
Hello, is this project dead? We've done a few of PRs and nothing has been viewed or merged. We are just asking because it takes more and more work to dissociate the code we've modified for a single feature, from the code we've updated with all the previous ones. 

If you do not plan to update the project or if you consider that the PRs should not be merged, we will stop making PRs on the original repository. :)

Have a nice day and thank you for your work!

**Comment by yanmarinich** [comment]
@CamilleHbp  Hi) first of all thank you for contributing to this project) well, it depends... I've sent an invitation) if you have any questions feel free to mail me yanmarinich@gmail.com because I have a lot of accounts also on different platforms
